# Generated by Django 4.0.6 on 2022-08-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='horario',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='planes',
            name='cantidad_clases',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='precio',
            field=models.IntegerField(blank=True),
        ),
    ]
