# Generated by Django 4.0.6 on 2022-08-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_actividades_horario_planes_cantidad_clases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='cantidad_clases',
            field=models.IntegerField(blank=True),
        ),
    ]
