# Generated by Django 4.0.6 on 2022-08-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_planes_cantidad_clases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='cantidad_clases',
            field=models.IntegerField(default=30),
        ),
    ]
