# Generated by Django 4.0.6 on 2022-08-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_planes_cantidad_clases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
