# Generated by Django 4.0.6 on 2022-09-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_socios_cuota_paga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='cuota_paga',
            field=models.BooleanField(null=True),
        ),
    ]
