# Generated by Django 4.0.6 on 2022-08-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_contacto_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
