# Generated by Django 4.0.6 on 2022-08-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_contacto_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_creacion',
        ),
    ]
