# Generated by Django 4.0.6 on 2022-08-29 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_alter_contacto_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
    ]
