# Generated by Django 4.0.6 on 2022-08-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_remove_contacto_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
