# Generated by Django 4.0.6 on 2022-08-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_remove_contacto_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(max_length=500),
        ),
    ]
